### ISSUE TITLE
clover bug

### ISSUE THREAD

**Issue by Kizanpa** [BTW-Community/SocksCrops#36]
BTW CE VERSION: 2.1.4
SC VERSION: 2.0.0
OTHER ADDONS (with versions): [compasspositioning-fabric-1.0.0], [craft-guide-3.0.2], [Deco-Addon-4.1.2], [dynamiclight-fabric-1.1.0], [map-markers-addon-2.2.5], [neodymium-btw-0.2.1]
MULTIPLAYER (yes/no): no
ISSUE (be as specific as possible): when right click a clover with empty hand, game crashed
STEPS TO REPRODUCE (even if obvious): right click a clover with empty hand
CRASH LOG (if there was a crash):
[crash-2024-12-22_18.55.08-client.txt](https://github.com/user-attachments/files/18221597/crash-2024-12-22_18.55.08-client.txt)

**Comment by socklessthing** [comment]
Fixed for next release.
